#!/bin/bash
# Assemble a .app bundle by hand. SwiftPM has no app-bundle product type and
# CLT-only has no xcodebuild, so this is the whole packaging step.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="${CONFIG:-debug}"
APP="$ROOT/build/Tsuyaku.app"
IDENTITY="${IDENTITY:-Tsuyaku Dev}"

# Marketing version comes from the VERSION file; the release workflow overrides
# it from the tag so a tagged build can never disagree with its own tag.
VERSION="${VERSION:-$(tr -d '[:space:]' < "$ROOT/VERSION")}"
# CFBundleVersion must increase monotonically across releases of the same
# marketing version. The commit count does that for free and needs no state.
BUILD="${BUILD:-$(git -C "$ROOT" rev-list --count HEAD 2>/dev/null || echo 1)}"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$ROOT/.build/$CONFIG/Tsuyaku" "$APP/Contents/MacOS/Tsuyaku"
cp "$ROOT/Info.plist"             "$APP/Contents/Info.plist"
printf 'APPL????' > "$APP/Contents/PkgInfo"

# Icons are generated by `make icon` and committed, so a plain `make bundle`
# needs no Swift-script step. Missing icons are a warning, not a failure: the
# app runs fine without them and falls back to the SF Symbol in the menu bar.
if [ -f "$ROOT/Resources/AppIcon.icns" ]; then
  cp "$ROOT/Resources/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
  cp "$ROOT/Resources/MenuBarIconTemplate.pdf" "$APP/Contents/Resources/MenuBarIconTemplate.pdf"
else
  echo "!! Resources/AppIcon.icns missing -- run 'make icon'. Bundling without icons."
fi

# Stamp the version *before* signing: any edit to Info.plist after codesign
# invalidates the signature.
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" "$APP/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD"              "$APP/Contents/Info.plist"

if security find-identity -p codesigning | grep -q "\"$IDENTITY\""; then
  codesign --force --options runtime \
           --entitlements "$ROOT/Tsuyaku.entitlements" \
           --sign "$IDENTITY" "$APP"
else
  echo "!! Identity '$IDENTITY' not found -- falling back to AD-HOC signing."
  echo "!! TCC permissions will NOT survive rebuilds. Run scripts/make-cert.sh."
  codesign --force --options runtime \
           --entitlements "$ROOT/Tsuyaku.entitlements" \
           --sign - "$APP"
fi

echo
echo "==> Designated Requirement (must NOT contain 'cdhash'):"
codesign -d -r- "$APP" 2>&1 | sed 's/^/    /'
echo "==> Bundle: $APP ($VERSION build $BUILD)"
